Create folders for layouts
mubanjs/muban-skeleton pull request #17
Opened 2021-06-14 14:20 UTC by pigeonfresh

I want to suggest to wrap the files for layouts in a folder

2021-06-18 11:59 UTC, larsvanbraam approved these changes

2021-06-29 14:49 UTC, ThijsTyZ requested changes

2021-06-29 14:49 UTC, ThijsTyZ commented on src/App.template.ts
> +import { layoutCustomTemplate } from './components/layouts/custom/CustomLayout.template';
```suggestion
import { customLayoutTemplate } from './components/layouts/custom/CustomLayout.template';
```
We should also rename the function as it is not following our Coding Standard

2021-07-15 16:35 UTC, ThijsTyZ approved these changes

2021-07-15 16:35 UTC, merged